export const legacyTokenGrantFactoryAbi = [
  {
    type: "function",
    name: "createGrant",
    stateMutability: "payable",
    inputs: [
      { name: "holder", type: "address" },
      { name: "token", type: "address" },
      { name: "paymentToken", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "price", type: "uint256" },
      { name: "expiry", type: "uint256" },
      { name: "vestingCliff", type: "uint256" },
      { name: "vestingEnd", type: "uint256" },
      { name: "salt", type: "bytes32" },
    ],
    outputs: [{ name: "grant", type: "address" }],
  },
  {
    type: "function",
    name: "predictGrantAddress",
    stateMutability: "view",
    inputs: [{ name: "salt", type: "bytes32" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "creationFee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "tokenGrantLogic",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
] as const;
