import { describe, expect, test } from "bun:test";
import { readFile } from "node:fs/promises";
import {
  boardroomAbi,
  boardroomFactoryAbi,
  liquidityLockerAbi,
  liquidityLockerFactoryAbi,
  pledgeCashAbis,
  pledgeCashDefaultPublicChainId,
  pledgeCashNetworkProfiles,
  positionManagerAbi,
  tokenGrantAbi,
  tokenGrantFactoryAbi,
} from "../src";

describe("generated SDK exports", () => {
  test("contains only the lean protocol ABI inventory", () => {
    expect(Object.keys(pledgeCashAbis)).toEqual([
      "Boardroom",
      "BoardroomFactory",
      "BoardroomToken",
      "ERC20",
      "LiquidityLocker",
      "LiquidityLockerFactory",
      "PositionManager",
      "TokenGrant",
      "TokenGrantFactory",
    ]);
    expect(pledgeCashAbis.Boardroom).toBe(boardroomAbi);
    expect(pledgeCashAbis.BoardroomFactory).toBe(boardroomFactoryAbi);
    expect(pledgeCashAbis.LiquidityLocker).toBe(liquidityLockerAbi);
    expect(pledgeCashAbis.LiquidityLockerFactory).toBe(liquidityLockerFactoryAbi);
    expect(pledgeCashAbis.PositionManager).toBe(positionManagerAbi);
    expect(pledgeCashAbis.TokenGrantFactory).toBe(tokenGrantFactoryAbi);
    expect("ProtocolFeeRouter" in pledgeCashAbis).toBe(false);
    expect("PledgeCashDeterministicDeployer" in pledgeCashAbis).toBe(false);
  });

  test("tracks the frozen lifecycle, grant, and locker functions", () => {
    expect(functionNames(boardroomAbi)).toEqual(expect.arrayContaining([
      "beginSnapshot",
      "claimRedemptionAsset",
      "execute",
      "executeBatch",
      "executeEscrow",
      "openRedemptions",
      "redeem",
      "startWindDown",
    ]));
    expect(functionNames(tokenGrantAbi)).toEqual(expect.arrayContaining([
      "getSettlementCost",
      "getSettleableAmount",
      "isQuarantined",
      "transferable",
    ]));
    expect(functionNames(tokenGrantFactoryAbi)).toEqual(expect.arrayContaining([
      "createGrant",
      "predictGrantAddress",
    ]));
    expect(functionNames(liquidityLockerFactoryAbi)).toEqual(expect.arrayContaining([
      "createLocker",
    ]));
    expect(functionNames(liquidityLockerAbi)).toEqual(expect.arrayContaining([
      "collectFees",
      "exit",
      "registerPosition",
    ]));
  });

  test("includes canonical network profiles", () => {
    expect(pledgeCashDefaultPublicChainId).toBe(11155111);
    expect(pledgeCashNetworkProfiles.map((profile) => profile.key)).toEqual([
      "ethereum-sepolia",
      "base-sepolia",
      "ethereum",
      "base",
      "arbitrum",
      "robinhood-chain",
    ]);
    expect(Object.keys(pledgeCashNetworkProfiles[0]!).sort()).toEqual([
      "chainId",
      "defaultRpcUrl",
      "environment",
      "explorer",
      "key",
      "name",
      "nativeCurrency",
      "wrappedNative",
    ]);
    expect(Object.keys(pledgeCashNetworkProfiles[0]!.wrappedNative)).toEqual(["symbol"]);
  });

  test("marks generated source and lean deployment fields", async () => {
    const source = await readFile(new URL("../src/generated.ts", import.meta.url), "utf8");
    expect(source).toContain("This file is generated by packages/sdk/scripts/generate.ts.");
    expect(source).toContain("liquidityLockerFactory?: Address;");
    expect(source).toContain("liquidityLockerFactoryCodeHash?: string;");
    expect(source).toContain("releaseCodeHash?: string;");
    expect(source).toContain("protocolOwner?: Address;");
    expect(source).toContain("protocolTreasury?: Address;");
  });
});

function functionNames(abi: readonly { type: string; name?: string }[]): string[] {
  return abi.flatMap((item) => item.type === "function" && item.name ? [item.name] : []);
}
