import { describe, expect, test } from "bun:test";
import { readFile } from "node:fs/promises";
import {
  ammFactoryAbi,
  ammPoolAbi,
  ammRouterAbi,
  distributionFactoryAbi,
  fixedPriceSaleAbi,
  lockedLiquidityAbi,
  lockedLiquidityFactoryAbi,
  pledgeCashAbis,
  pledgeCashDeployments,
  poolFeesAbi,
  tokenGrantFactoryAbi,
} from "../src";

describe("generated SDK exports", () => {
  test("includes core contract ABIs", () => {
    expect(pledgeCashAbis.TokenGrantFactory).toBe(tokenGrantFactoryAbi);
    expect(pledgeCashAbis.DistributionFactory).toBe(distributionFactoryAbi);
    expect(pledgeCashAbis.AmmFactory).toBe(ammFactoryAbi);
    expect(pledgeCashAbis.AmmPool).toBe(ammPoolAbi);
    expect(pledgeCashAbis.AmmRouter).toBe(ammRouterAbi);
    expect(pledgeCashAbis.LockedLiquidity).toBe(lockedLiquidityAbi);
    expect(pledgeCashAbis.LockedLiquidityFactory).toBe(lockedLiquidityFactoryAbi);
    expect(pledgeCashAbis.PoolFees).toBe(poolFeesAbi);
    expect(tokenGrantFactoryAbi.some((item) => item.type === "function" && item.name === "createGrant")).toBe(true);
    expect(tokenGrantFactoryAbi.some((item) => item.type === "function" && item.name === "predictGrantAddress")).toBe(true);
    expect(distributionFactoryAbi.some((item) => item.type === "function" && item.name === "createFixedPriceSale")).toBe(true);
    expect(fixedPriceSaleAbi.some((item) => item.type === "function" && item.name === "buy")).toBe(true);
    expect(ammRouterAbi.some((item) => item.type === "function" && item.name === "swapExactTokensForTokens")).toBe(true);
    expect(lockedLiquidityFactoryAbi.some((item) => item.type === "function" && item.name === "createLockedLiquidity")).toBe(true);
  });

  test("includes checked-in deployment metadata", () => {
    expect(pledgeCashDeployments[998]?.chainId).toBe(998);
    expect(pledgeCashDeployments[998]?.tokenGrantFactory).toBe("0xFCbfb61330d418f189A0594993E72BBd0b81E8aF");
    expect(pledgeCashDeployments[998]?.creationFee).toBe(100000000000000000n);
    expect(pledgeCashDeployments[998]?.boardroomStatus).toBe("pending");
    expect(pledgeCashDeployments[998]?.boardroomFactory).toBeUndefined();
    expect(pledgeCashDeployments[998]?.distributionFactory).toBeUndefined();
  });

  test("marks generated source as generated", async () => {
    const source = await readFile(new URL("../src/generated.ts", import.meta.url), "utf8");
    expect(source).toContain("This file is generated by packages/sdk/scripts/generate.ts.");
  });
});
