import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { loadNetworkManifest } from "../../contracts/script/network-profiles";

type Artifact = {
  abi?: unknown;
};

type DeploymentFieldKind = "address" | "bigint" | "number" | "string";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, "../../..");
const outFile = join(repoRoot, "packages/sdk/src/generated.ts");

const contracts = [
  ["Boardroom", "packages/contracts/out/Boardroom.sol/Boardroom.json", "boardroomAbi"],
  ["BoardroomFactory", "packages/contracts/out/BoardroomFactory.sol/BoardroomFactory.json", "boardroomFactoryAbi"],
  ["BoardroomToken", "packages/contracts/out/BoardroomToken.sol/BoardroomToken.json", "boardroomTokenAbi"],
  ["ERC20", "packages/contracts/out/ERC20.sol/ERC20.json", "erc20Abi"],
  ["LiquidityLocker", "packages/contracts/out/LiquidityLocker.sol/LiquidityLocker.json", "liquidityLockerAbi"],
  ["LiquidityLockerFactory", "packages/contracts/out/LiquidityLockerFactory.sol/LiquidityLockerFactory.json", "liquidityLockerFactoryAbi"],
  ["PositionManager", "packages/contracts/out/IPositionManager.sol/IPositionManager.json", "positionManagerAbi"],
  ["TokenGrant", "packages/contracts/out/TokenGrant.sol/TokenGrant.json", "tokenGrantAbi"],
  ["TokenGrantFactory", "packages/contracts/out/TokenGrantFactory.sol/TokenGrantFactory.json", "tokenGrantFactoryAbi"],
] as const;

const deploymentFields = [
  ["chainId", "number"],
  ["status", "string"],
  ["reason", "string"],
  ["protocolVersion", "string"],
  ["releaseCodeHash", "string"],
  ["sourceCommit", "string"],
  ["deterministicDeployer", "address"],
  ["deterministicDeployerOwner", "address"],
  ["create2Factory", "address"],
  ["boardroomFactory", "address"],
  ["boardroomImplementation", "address"],
  ["manifestHash", "string"],
  ["boardroomArchitectureCodeHash", "string"],
  ["moduleArchitectureCodeHash", "string"],
  ["protocolFeeRouter", "address"],
  ["uniswapV4PoolManager", "address"],
  ["uniswapUniversalRouter", "address"],
  ["uniswapV4Quoter", "address"],
  ["uniswapV4StateView", "address"],
  ["uniswapV4PositionManager", "address"],
  ["permit2", "address"],
  ["liquidityLockerFactory", "address"],
  ["tokenGrantFactory", "address"],
  ["tokenGrantLogic", "address"],
  ["wrappedNative", "address"],
  ["protocolOwner", "address"],
  ["protocolTreasury", "address"],
  ["creationFee", "bigint"],
  ["deploymentBlock", "bigint"],
  ["deterministicDeployerCodeHash", "string"],
  ["protocolFeeRouterCodeHash", "string"],
  ["boardroomFactoryCodeHash", "string"],
  ["boardroomImplementationCodeHash", "string"],
  ["tokenGrantFactoryCodeHash", "string"],
  ["tokenGrantLogicCodeHash", "string"],
  ["liquidityLockerFactoryCodeHash", "string"],
  ["uniswapV4PoolManagerCodeHash", "string"],
  ["uniswapUniversalRouterCodeHash", "string"],
  ["uniswapV4QuoterCodeHash", "string"],
  ["uniswapV4StateViewCodeHash", "string"],
  ["uniswapV4PositionManagerCodeHash", "string"],
  ["permit2CodeHash", "string"],
  ["wrappedNativeCodeHash", "string"],
] as const satisfies readonly (readonly [string, DeploymentFieldKind])[];

function literal(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function deploymentFieldType(kind: DeploymentFieldKind): string {
  if (kind === "address") return "Address";
  if (kind === "bigint") return "bigint";
  if (kind === "number") return "number";
  return "string";
}

async function readAbi(path: string): Promise<unknown[]> {
  const artifact = JSON.parse(await readFile(join(repoRoot, path), "utf8")) as Artifact;
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`Missing ABI in ${path}`);
  }
  return artifact.abi;
}

const abiExports: string[] = [];
const abiMapEntries: string[] = [];

for (const [contractName, artifactPath, exportName] of contracts) {
  const abi = await readAbi(artifactPath);
  abiExports.push(`export const ${exportName} = ${literal(abi)} as const;`);
  abiMapEntries.push(`${contractName}: ${exportName}`);
}

const networkManifest = await loadNetworkManifest();
const publicNetworkProfiles = networkManifest.profiles.map((profile) => ({
  chainId: profile.chainId,
  key: profile.key,
  name: profile.name,
  environment: profile.environment,
  defaultRpcUrl: profile.defaultRpcUrl,
  explorer: profile.explorer,
  nativeCurrency: profile.nativeCurrency,
  wrappedNative: {
    symbol: profile.wrappedNative.symbol,
  },
}));
const deploymentTypeFields = deploymentFields
  .map(([field, kind]) => `  ${field}${field === "chainId" ? "" : "?"}: ${deploymentFieldType(kind)};`)
  .join("\n");

const source = `// This file is generated by packages/sdk/scripts/generate.ts.
// Do not edit it by hand.

import type { Address } from "viem";

export type PledgeCashDeployment = {
${deploymentTypeFields}
};

export type PledgeCashNetworkProfile = {
  readonly chainId: number;
  readonly key: string;
  readonly name: string;
  readonly environment: "testnet" | "mainnet";
  readonly defaultRpcUrl: string;
  readonly explorer: {
    readonly name: string;
    readonly url: string;
  };
  readonly nativeCurrency: {
    readonly name: string;
    readonly symbol: string;
    readonly decimals: number;
  };
  readonly wrappedNative: {
    readonly symbol: string;
  };
};

export const pledgeCashDefaultPublicChainId = ${networkManifest.supportPolicy.defaultChainId} as const;

export const pledgeCashNetworkProfiles = ${literal(publicNetworkProfiles)} as const satisfies readonly PledgeCashNetworkProfile[];

export type PledgeCashNetworkKey = typeof pledgeCashNetworkProfiles[number]["key"];

${abiExports.join("\n\n")}

export const pledgeCashAbis = {
  ${abiMapEntries.join(",\n  ")}
} as const;
`;

await mkdir(dirname(outFile), { recursive: true });
await writeFile(outFile, source);
